name = "knot-and-pins-app"
pages_build_output_dir = "dist"
compatibility_date = "2024-03-31"

[[d1_databases]]
binding = "DB"
database_name = "knot-db"
database_id = "24b8bd2a-224c-412f-af46-e8fc948f5673"
